name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: []
assignees: []
body:
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft Version
      description: The version of Minecraft you are using
      options:
        - "1.20.5-SNAPSHOT"
        - "1.20.4"
        - "1.20.3"
        - "1.20.2"
        - "1.20.1"
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod Loader
      description: The mod loader you are using
      options:
        - Fabric
        - Quilt
        - Forge
        - NeoForge
    validations:
      required: true
  - type: input
    id: mod-loader-version
    attributes:
      label: Mod Loader Version
      description: The version of the mod loader you are using
      placeholder: e.x. 45.1.0
    validations:
      required: true
  - type: input
    id: arch-api-version
    attributes:
      label: Architectury API Version
      description: The version of the Architectury API you are using
      placeholder: e.x. 9.1.12
    validations:
      required: true
  - type: input
    id: fcapi-port-version
    attributes:
      label: FCAPI Port (if present) Version
      description: The version of the Forge Config API Port you are using (Only applicable to Fabric / Quilt).
      placeholder: e.x. 8.0.0
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the bug
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: crash-reports-logs
    attributes:
      label: Crash Reports/Logs
      description: Crash reports / logs hosted on [pastebin](https://pastebin.com), [mclogs](https://mclo.gs), [gist](https://gist.github.com), etc.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenhots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Link(s) to any applicable screenshot(s)
  - type: textarea
    id: mod-list
    attributes:
      label: Mod List
      description: If applicable, include the list of mods that were enabled when the bug occurred, or NONE if there were no extras. We would prefer if you entered this on a paste site such as [pastebin](https://pastebin.com) or hastebin.
      placeholder: List of mods
    validations:
      required: true
