name: Feature Request
description: Suggest an idea for the mod
title: "[Feature Request]: "
labels: ["Feature Request"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for submitting this feature request!
        
        **ONLY ONE FEATURE REQUEST PER ISSUE!**
  - type: textarea
    id: description
    attributes:
      label: Description of feature request
      placeholder: "Describe what you'd like to see in the mod. Don't spare the details!"
    validations:
      required: true
